#!/usr/bin/env python3
"""Table 4: the pre-registration ledger.

Every effect size and interval is read from outputs/artifacts/ at build time.
Only the REGISTERED acceptance text and the verdict word are carried in this
file, because those live in docs/METHOD_FREEZE.md and are not machine
readable. Nothing numeric is typed by hand.

  python3 scripts/paper/table4_ledger.py
  -> outputs/tables/table4_ledger.tex   (booktabs, drops into the paper)
  -> outputs/tables/table4_ledger.txt   (plain text, for review)
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ART = os.path.join(ROOT, "outputs", "artifacts")
OUT = os.path.join(ROOT, "outputs", "tables")


def J(name):
    with open(os.path.join(ART, name)) as fh:
        return json.load(fh)


def ci(point, lo, hi):
    return f"{point:+.4f} [{lo:+.4f}, {hi:+.4f}]"


def build():
    h2 = J("h2_max_test.json")
    tmp = J("temporal_observability.json")["2.0"]
    vox = J("baselines.json")["contrasts"]
    obj = J("baselines_object.json")["contrasts"]
    sel_s = J("selective_max_nonfree.json")
    sel_f = J("selective_max_full.json")

    rows = [
        # id, hypothesis, registered acceptance, result, verdict
        ("H1", "Calibration gap declines monotonically with observability decile",
         r"strictly monotone, $\rho \le -0.50$",
         r"2 reversals, $\rho = -0.433$", "FAILS"),

        ("H2", "Observability outranks \\texttt{mask\\_camera} on per-voxel error",
         "interval excludes zero",
         ci(h2["diff"], h2["ci"][0], h2["ci"][1]), "HOLDS"),

        ("H4", "Temporal observability outranks the instantaneous map",
         "interval excludes zero, half-life fixed at 2\\,s",
         ci(tmp["delta"], tmp["lo"], tmp["hi"]), "HOLDS"),

        ("H5", "Combined score beats observability alone, per voxel",
         "interval excludes zero",
         ci(*vox["combined_minus_observability"]), "HOLDS"),

        ("H6", "Combined score beats the model's own confidence, per voxel",
         "interval excludes zero",
         ci(*vox["combined_minus_MSP"]), "HOLDS"),

        ("S1", "Selective risk improves on the sensor-only volume",
         "interval excludes zero",
         ci(*sel_s["boot_margin_sensor_mask_minus_obs"]), "HOLDS"),

        ("S2", "Selective risk improves on the full volume",
         "interval excludes zero",
         ci(*sel_f["boot_margin_sensor_mask_minus_obs"]), "NULL"),

        ("R1", "Observability-conditioned recalibration beats global, on ECE",
         "interval excludes zero",
         ci(*sel_s["boot_ece_global_minus_obs"]), "TIES"),

        ("E1", "Observability outranks confidence \\emph{per object}",
         "exploratory, reported either way",
         ci(*obj["observability - MSP"]), "HOLDS"),

        ("E2", "Observability matches a LiDAR point-count oracle, per object",
         "exploratory, reported either way",
         ci(*obj["observability - LiDAR ORACLE"]), "TIES"),

        ("H3", "Error increases with time since observability last exceeded 0.15",
         "interval excludes zero",
         "not yet run", "PENDING"),

        ("H2$'$", "H2 replicates on a second backbone (SurroundOcc)",
         r"$\ge +0.02$ and interval excludes zero",
         "not yet run", "PENDING"),
    ]
    return rows, h2


def main():
    rows, h2 = build()
    os.makedirs(OUT, exist_ok=True)

    # ------------------------------------------------------------ plain text
    w = [4, 62, 44, 30, 8]
    lines = []
    hdr = ("id", "hypothesis", "registered in advance", "result", "verdict")
    lines.append("  ".join(h.ljust(x) for h, x in zip(hdr, w)))
    lines.append("  ".join("-" * x for x in w))
    for r in rows:
        clean = [str(c).replace("\\texttt{", "").replace("\\emph{", "")
                 .replace("}", "").replace("\\,", " ").replace("$", "")
                 .replace("\\rho", "r").replace("\\le", "<=").replace("\\ge", ">=")
                 for c in r]
        lines.append("  ".join(c[:x].ljust(x) for c, x in zip(clean, w)))
    txt = "\n".join(lines)
    with open(os.path.join(OUT, "table4_ledger.txt"), "w") as fh:
        fh.write(txt + "\n")

    # ----------------------------------------------------------------- latex
    tex = [
        r"% generated by scripts/paper/table4_ledger.py -- do not edit by hand",
        r"\begin{table*}[t]",
        r"\centering\small",
        r"\caption{\textbf{The pre-registration ledger.} Every hypothesis was "
        r"written into an append-only log with its acceptance criterion before "
        r"the data existed; each entry states whether it was decided before or "
        r"after seeing data. Effect sizes are paired scene-bootstrap means with "
        r"95\\% intervals on the sealed test split "
        rf"({h2['scenes']} scenes, {h2['frames']:,} frames). "
        r"Four of the twelve entries did not survive.}",
        r"\label{tab:ledger}",
        r"\begin{tabular}{llllc}",
        r"\toprule",
        r" & Hypothesis & Registered in advance & Result & Verdict \\",
        r"\midrule",
    ]
    for rid, hyp, reg, res, verdict in rows:
        mark = {"HOLDS": r"\textbf{holds}", "FAILS": r"\textsc{fails}",
                "NULL": r"\textsc{null}", "TIES": r"\textsc{ties}",
                "PENDING": r"\textit{pending}"}[verdict]
        tex.append(f"{rid} & {hyp} & {reg} & {res} & {mark} \\\\")
    tex += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    with open(os.path.join(OUT, "table4_ledger.tex"), "w") as fh:
        fh.write("\n".join(tex) + "\n")

    print(txt)
    print()
    print("wrote outputs/tables/table4_ledger.{tex,txt}")


if __name__ == "__main__":
    main()
